namespace HNC
{
    public enum HncSystem
    {
        HNC_SYS_CHAN_NUM = 0,
        HNC_SYS_MOVE_UNIT = 1,
        HNC_SYS_TURN_UNIT = 2,
        HNC_SYS_METRIC_DISP = 3,
        HNC_SYS_SHOW_TIME = 4,
        HNC_SYS_POP_ALARM = 5,
        HNC_SYS_GRAPH_ERASE = 6,
        HNC_SYS_MAC_TYPE = 7,
        HNC_SYS_PREC = 8,
        HNC_SYS_F_PREC = 9,
        HNC_SYS_S_PREC = 10,
        HNC_SYS_NCK_VER = 11,
        HNC_SYS_DRV_VER = 12,
        HNC_SYS_PLC_VER = 13,
        HNC_SYS_CNC_VER = 14,
        HNC_SYS_MCP_KEY = 15,
        HNC_SYS_ACTIVE_CHAN = 16,
        HNC_SYS_REQUEST_CHAN = 17,
        HNC_SYS_MDI_CHAN = 18,
        HNC_SYS_REQUEST_CHAN_MASK = 19,
        HNC_SYS_CHAN_MASK = 20,
        HNC_SYS_PLC_STOP = 21,
        HNC_SYS_POWEROFF_ACT = 22,
        HNC_SYS_IS_HOLD_REDECODE = 23,
        HNC_SYS_NC_VER = 24,
        HNC_SYS_SN_NUM = 25,
        HNC_SYS_MACHINE_TYPE = 26,
        HNC_SYS_MACHINE_INFO = 27,
        HNC_SYS_MACFAC_INFO = 28,
        HNC_SYS_USER_INFO = 29,
        HNC_SYS_MACHINE_NUM = 30,
        HNC_SYS_EXFACTORY_DATE = 31,
        HNC_SYS_ACCESS_LEVEL = 32,
        HNC_SYS_MUL_CHAN_RESET = 33,
        HNC_SYS_RIGHTS_KEY = 34,
        HNC_SYS_TOTAL = 35,
    }

    public enum HncRegType
    {
        REG_TYPE_X = 0,
        REG_TYPE_Y = 1,
        REG_TYPE_F = 2,
        REG_TYPE_G = 3,
        REG_TYPE_R = 4,
        REG_TYPE_W = 5,
        REG_TYPE_D = 6,
        REG_TYPE_B = 7,
        REG_TYPE_P = 8,
        REG_TYPE_TOTAL = 9,
    }
}
